---
name: MoneyPouch
main: Daniktheboss\MoneyPouch\Main
version: 0.0.1
api:
- 3.0.0-ALPHA5
- 3.0.0-ALPHA6
- 3.0.0-ALPHA7
- 3.0.0-ALPHA9
author: Daniktheboss
description: Get random amount of money using a pouch
commands:
  moneypouch:
    description: Give player money pouches!
...
